version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
    driver: local
