name:  sonic-connect-deployment

on:
  workflow_run:
    workflows: [sonic-connect-gh-actions]
    branches: [main]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Sign in via Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        imageToBuild: sonicconnectacr.azurecr.io/sonic-connect:${{ github.sha }}
        acrName: sonicconnectacr
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        resourceGroup: sonic-connect
        containerAppName: sonic-connect-container-app
