name:  sonic-connect deployment

on:
  # Automatically trigger it when detected changes in repo
  push:
    # Branches to look out for changes on
    branches:
      # Listen for changes on main branch
      [ main ]

  # Allow manually trigger of the jobs
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Sign in via Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        imageToBuild: sonicconnectacr.azurecr.io/sonic-connect:latest
        acrName: sonicconnectacr
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        resourceGroup: sonic-connect
        containerAppName: sonic-connect-container-app
